# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [3]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [5]:
arr=np.arange(10,20)
print(arr)

arr=np.arange(10,20)

[10 11 12 13 14 15 16 17 18 19]


### Step 3. Reshape 1D to 2D Array

In [27]:
arr=np.array([1,3,5,7,9,11,13,15,24])
reshape = arr.reshape(3,3)
print(reshape)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 24]]


### Step 4. Create a Linspace array

In [7]:
np.linspace(12,18,26)

array([12.  , 12.24, 12.48, 12.72, 12.96, 13.2 , 13.44, 13.68, 13.92,
       14.16, 14.4 , 14.64, 14.88, 15.12, 15.36, 15.6 , 15.84, 16.08,
       16.32, 16.56, 16.8 , 17.04, 17.28, 17.52, 17.76, 18.  ])

### Step 5. Create a Random Numbered Array

In [15]:
np.random.rand(5,10)

array([[0.86369377, 0.83467832, 0.83808896, 0.96082202, 0.27529617,
        0.06792352, 0.02622778, 0.64526026, 0.32366493, 0.02135949],
       [0.88223518, 0.26682746, 0.45370566, 0.53561666, 0.11738183,
        0.09258208, 0.1826269 , 0.34128593, 0.2159981 , 0.57734703],
       [0.9670877 , 0.32490124, 0.16765458, 0.12850021, 0.39797427,
        0.13687525, 0.8748391 , 0.64889004, 0.20545026, 0.67830864],
       [0.88273055, 0.89423062, 0.54314407, 0.03802635, 0.78393169,
        0.26842349, 0.76069149, 0.64973615, 0.40402222, 0.30096733],
       [0.21801933, 0.90986056, 0.37498073, 0.84112382, 0.80386092,
        0.73308201, 0.55244679, 0.34821017, 0.53007894, 0.16795292]])

### Step 6. Create a Random Integer Array

In [31]:
np.random.randint(10,100,size=(4,4))

array([[56, 99, 57, 90],
       [70, 77, 67, 94],
       [91, 31, 67, 18],
       [77, 54, 97, 70]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [75]:
arr2 = np.random.randint(10,50,size=10)
print(arr2)

[11 32 44 27 12 25 20 45 21 32]


In [84]:
print("max no. is =",arr2.max())
print("min no. is =",arr2.min())
print("ArgMax no. is =",arr2.argmax())
print("ArgMin no. is =",arr2.argmin())

max no. is = 45
min no. is = 11
ArgMax no. is = 7
ArgMin no. is = 0


### Step 8. Indexing in 1D Array

In [90]:
arr3 = np.random.randint(10,100,size=9)
print(arr3)

[99 65 16 19 56 44 69 59 62]
69


In [92]:
print(arr3[6])

69


In [101]:
print(arr3[2:3])

[16]


### Step 9. Indexing in 2D Array

In [94]:
arr4 = np.random.randint(10,100,size=(5,5))
print(arr4)

[[76 54 40 97 45]
 [42 18 70 57 65]
 [51 85 36 10 14]
 [81 67 92 93 46]
 [22 20 78 27 39]]


In [96]:
print(arr4[3])

[81 67 92 93 46]


In [98]:
print(arr4[2][3])

10


In [103]:
print(arr4[0:2,1:])

[[54 40 97 45]
 [18 70 57 65]]


### Step 10. Conditional Selection

In [107]:
arr5 = np.random.randint(10,100,size=8)
print(arr5)

[86 54 47 53 92 62 38 78]


In [111]:
arr5[arr5>20]

array([86, 54, 47, 53, 92, 62, 38, 78])

In [115]:
arr5[(22<arr5)&(arr5<42)]

array([38])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [5]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|",index_col='user_id')
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [7]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [9]:
users.head(10)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703

### Step 6. What is the number of observations in the dataset?

In [11]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [13]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [15]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [17]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [19]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [167]:
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [161]:
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [21]:
users['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [169]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [171]:
users.describe(include='all')

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [173]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [177]:
users['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [23]:
users['age'].value_counts().tail(10)

age
70    3
62    2
68    2
64    2
69    2
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

### You're not just learning, you're mastering it. Keep aiming higher! 🚀